Deployment setup
opencopilotdev/docs pull request #21
Opened 2023-09-15 18:15 UTC by KasparPeterson

2023-09-15 20:17 UTC, kristjanpeterson1 commented on integrate/front-end.mdx
> +Open the created file in browser and enjoy.
A bit strange thing to say here imo

2023-09-15 20:19 UTC, kristjanpeterson1 approved these changes

2023-09-19 18:21 UTC, taivop requested changes

2023-09-19 19:18 UTC, KasparPeterson commented on integrate/front-end.mdx
> +Build the front-end library:
The usage would be to just use the embedded html example imo. We can add that and add a link to the frontend-library github if users want to actually build and modify the raw source.

2023-09-19 20:16 UTC, taivop approved these changes

2023-09-19 20:51 UTC, merged